server: # Configuracao do servidor
  port: 8080 # Porta que a aplicacao ira rodar

spring: # Configuracao do spring
  application:
    name: client-app # Nome que a aplicacao tera

  cloud:
    open-feign:
      client:
        config:
          viaCepClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC

  sql: # Configuracao do JPA
    init: # Ao incializar
      continue-on-error: true # Se a conexao falhar, a aplicacao continua a rodar

  datasource: # ???
    url: jdbc:postgresql://localhost:5432/postgres # URL da conexao, no caso, o docker na porta 5432
    username: admin # Usuario para conectar
    password: root # Senha para conectar
    driver-class-name: org.postgresql.Driver # Driver do banco utilizado
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 600000
      initialization-fail-timeout: -1
      validation-timeout: 1000

  jpa:  # Configuracao do JPA
    generate-ddl: false # Gerar as tabelas mapeadas com @Entity
    show-sql: true # Exibir codigos SQL no terminal

